# Generated by Django 2.1.5 on 2019-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('ca', models.CharField(max_length=100)),
                ('wa1', models.CharField(max_length=100)),
                ('wa2', models.CharField(max_length=100)),
            ],
        ),
    ]
